#!/bin/bash

yarn build && \
echo "Starting generating patterns..." && \
echo "This can take a few seconds." && \
node dist/src/index.js && \
cd output && for f in *.png; do convert $f -trim $f; done
